version: '3.4'
services:
  prysm-zinken-beacon-chain.dnp.dappnode.eth:
    image: 'prysm-zinken-beacon-chain.dnp.dappnode.eth:1.0.9'
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.0.0-alpha.27
    volumes:
      - 'data:/data'
    ports:
      - '13000'
      - '12000'
    restart: always
    environment:
      - 'HTTP_WEB3PROVIDER=http://goerli-geth.dappnode:8545'
      - EXTRA_OPTS
volumes:
  data: {}
